### ISSUE TITLE
Is duplicate prevention supported?

### ISSUE THREAD

**Issue by wsmoak** [chargify/chargify_api_ares#106]
https://docs.chargify.com/api-duplicate-prevention describes how to include a uniqueness_token attribute to avoid duplicates when using the API.

Can this be done with the gem as well?

**Comment by wsmoak** [comment]
I gave this a try but couldn't see how to introduce a second 'top level' element.  Working with subscription.rb and base.rb, any attributes you add are sent *inside* the subscription.  

The uniqueness_token needs to be at the same level as the subscription for it to work.

**Comment by caseykickserv** [comment]
@wsmoak I have not found a clean way to do this either.

**Comment by jeremywrowe** [comment]
Just as a heads up, I am working on adding Duplicate Protection to the gem. For more information: https://github.com/chargify/chargify_api_ares/pull/109

**Comment by wsmoak** [comment]
https://github.com/chargify/chargify_api_ares/pull/109 was merged a while ago... closing this.
