### ISSUE TITLE
Subscriptions without payment profiles

### ISSUE THREAD

**Issue by caseykickserv** [chargify/chargify_api_ares#108]
I really want to be able to create subscriptions without any payment profile. 

#### Business Case
* I want to allow users to sign up quickly (short form)
* I want to allow them to use the product for x days before requiring CC info
* After x days require customer to enter CC info in order to continue product usage.

#### Current State
When I attempted to do this using the Api a validation error was received.

error
```
   ["Payment profile: cannot be blank."]
```

Is there any way to get support for this?

**Comment by YesThatAllen** [comment]
We do this now using the Trial mode.  The only time it gets sketchy is if we need to extend their trial once they have entered dunning. At that point, we need to cancel the subscription, then reactivate it w balance reset, then set the new end-date.

**Comment by caseykickserv** [comment]
@YesThatAllen can you post a JSON example or more details about Trial mode?

**Comment by caseykickserv** [comment]
I found it in the product settings, thanks for checking my insanity. The product was simply configured wrong.

**Comment by YesThatAllen** [comment]
Awesome.

**Comment by wsmoak** [comment]
Looks like this was resolved with configuration, so I'll close it.
