### ISSUE TITLE
Unpaid invoices return all invoices

### ISSUE THREAD

**Issue by carsonreinke** [chargify/chargify_api_ares#136]
`Chargify::Invoice.unpaid` (https://github.com/chargify/chargify_api_ares/blob/master/lib/chargify_api_ares/resources/invoice.rb#L16) should just be removed, unless this will be added soon 😉

**Comment by speric** [comment]
@carsonreinke see https://github.com/chargify/chargify_api_ares/releases/tag/v1.4.6
