### ISSUE TITLE
Version of Chargify API being used

### ISSUE THREAD

**Issue by amymarco** [chargify/chargify_api_ares#151]
I don't see a version being supplied anywhere. Is this gem using the lastest version of the Chargify REST API? 

Thanks!

**Comment by wsmoak** [comment]
The Chargify API isn't versioned or gated, so all API calls, including via the gem, will get the same responses.

That said, the gem is a community maintained resource, so it's not guaranteed that it supports all of the available endpoints.  If something changes in the API, it may take some time before someone submits a pull request to add it to the gem.

**Comment by ivanovv** [comment]
Chargify now has V1 and V2 keys, which one to use with this gem?

![api_version](https://cloud.githubusercontent.com/assets/142624/22617370/b80e9e2c-eaf5-11e6-90ef-490ec16ee164.png)

**Comment by mwhagedorn** [comment]
Yup use V1
