### ISSUE TITLE
Customer Metadata?

### ISSUE THREAD

**Issue by bbrealnex** [chargify/chargify_api_ares#96]
I can't seem to add/modify Customer Metadata (for a given customer), only Subscription Metadata. Is Customer Metadata not supported yet?

**Comment by jeremywrowe** [comment]
Correct, the gem only supports Subscription Metadata currently.

**Comment by YesThatAllen** [comment]
We too are interested in options regarding metadata (which I assume includes custom fields)

**Comment by wsmoak** [comment]
I'm working on adding support for customer metadata -- so far it seems like a straightforward copy/paste/modify of what's already there for subscriptions will do it.

**Comment by wsmoak** [comment]
Customer Metadata is now available in version 1.3.5 of the gem.
